apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: user-ms
  name: user-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-ms
    spec:
      containers:
      - image: fernandoflores07081/user-ms-prod
        name: user-ms-prod
        env:
        - name: PORT
          value: "3006"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: DATABASE_URL
        resources: {}
status: {}
