apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-webhook
  name: payments-webhook
spec:
  ports:
  - name: "3003"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: payment-ms
  type: NodePort
status:
  loadBalancer: {}
